---
title: Codedthinking
description: Lorem ipsum dolorem
#url: https://codedthinking.com
baseurl: 
lang: en
permalink: "/:title/"

remote_theme: korenmiklos/remote-theme

website: blog # options: blog | courses | publications

google_analytics: 

paginate: 4
paginate_path: "/blog/:num/" 

markdown: kramdown
highlighter: rouge

plugins:
- jekyll-seo-tag
- jekyll-paginate
- jekyll-remote-theme

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"

livereload: true

collections:
  publications:
    output: false
  courses:
    output: false
  posts:
    output: true
    permalink: /:collection/:title

# Defaults
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: courses
    values:
      layout: course
  - scope:
      path: ""
      type: posts
    values:
      layout: post
