# File: .github/workflows/update-from-data.yml
name: Update from Data Repository

on:
  repository_dispatch:
    types: [update-from-data]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portfolio repository
        uses: actions/checkout@v3

      - name: Checkout data repository
        uses: actions/checkout@v3
        with:
          repository: korenmiklos/remote-theme
          path: temp-data

      - name: Update files from data repository
        run: |
          # List of files and folders to manage
          files_to_manage=(
            "_courses"
            "_data"
            "_posts"
            "_publications"
            "blog"
            "story.md"
            "home-blog.md"
            "search-blog.json"
            "index.md"  # Include this to ensure it's removed if it exists
            # Add more files or folders as needed
          )

          # Remove existing items using git rm
          for item in "${files_to_manage[@]}"; do
            if [ -e "$item" ]; then
              git rm -r "$item"
              echo "Removed $item from Git tracking"
            fi
          done

          # Copy items from temp-data
          for item in "${files_to_manage[@]}"; do
            if [ -e "temp-data/$item" ]; then
              cp -R "temp-data/$item" .
              git add "$item"
              echo "Copied and staged $item"
            else
              echo "Warning: $item not found in temp-data"
            fi
          done
          
          # Special handling for home-blog.md
          if [ -f "home-blog.md" ]; then
            git mv home-blog.md index.md
            echo "Renamed home-blog.md to index.md"
          else
            echo "home-blog.md not found, skipping rename"
          fi
      - name: Remove temp-data folder
        run: rm -rf temp-data
          
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update from data repository" || echo "No changes to commit"
          git push
